### ISSUE TITLE
not able use mango in maven projects

### ISSUE THREAD

**Issue by harschware** [feijoas/mango#1]
If you attempt to build a project that depends on Mango with Maven you will get something similar to:
2/24/15, 3:44:28 PM PST: [ERROR] Could not resolve artifact com.google.code.findbugs:jsr305:pom:1.3.+

See https://github.com/sbt/sbt/issues/1136 for background.

Maybe republishing with the latest sbt would resolve the issue?

**Comment by harschware** [comment]
Maybe changing it to provided scope would solve the issue:
https://code.google.com/p/guava-libraries/issues/detail?id=1096

WORK AROUND:

``` xml
        <dependency>
            <groupId>org.feijoas</groupId>
            <artifactId>mango_2.10</artifactId>
            <version>0.10</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.code.findbugs</groupId>
                    <artifactId>jsr305</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by mschneiderwng** [comment]
Hi harschware,

thanks for the work around! This is an issue related to Guava. 
The problem does not occur if you built with sbt so I guess updating sbt does not resolve the problem. Maybe the best would be to publish a maven pom with your work around.
