### ISSUE TITLE
Update to Guava 20

### ISSUE THREAD

**Issue by dmyersturnbull** [feijoas/mango#10]
This looks great, thanks!

**Comment by feijoas** [comment]
Thanks! I am currently waiting for [SI-5559](https://issues.scala-lang.org/browse/SI-5559) to be fixed before  I can update mango.

**Comment by feijoas** [comment]
I found a fix. 
You can checkout the development branch or wait until it is in master

**Comment by feijoas** [comment]
- the artifacts are now on maven central
- master is merged
