### ISSUE TITLE
Support Scala 2.11

### ISSUE THREAD

**Issue by wuservices** [feijoas/mango#2]
I'm using mango with 2.10 now mostly just for cache and it's been awesome! Are you still maintaining this and keeping up to date? It'd be great if a 2.11 jar was provided as well.

For my own use, could I just change the target version in SBT and rebuild?

**Comment by feijoas** [comment]
Dear Jon,

I updated the library to Scala 2.11 - please let me know if you have any problems.
I still maintain mango, however I am waiting for Guava to use Java 8 features.

**Comment by wuservices** [comment]
Thanks so much! Appreciate the super quick response.
