### ISSUE TITLE
put and remove for immutable RangeMap

### ISSUE THREAD

**Issue by scubamaggo** [feijoas/mango#4]
While put and remove are supported for the mutable RangeMap implementation, the immutable version does not have these methods (neither does the guava interface). When looking at the immutable scala collections, they all support modifying methods which just return a new collection. Wouldn't it make sense to implement something similar for the immutable Guava collections?

**Comment by feijoas** [comment]
I agree. But mango is just a wrapper around guava which does not support modification. 
Adding put and remove to mango would create the impression that we can do this modification efficiently (like the scala collections), which is not the case.
